name: CI/CD Deploy YoForex-AI Backend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Debug: show ~/.ssh contents
        run: |
          echo "SSH dir contents:"
          ls -la ~/.ssh

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host:        ${{ secrets.SSH_HOST }}         # e.g. 206.206.127.10
          username:    ${{ secrets.SSH_USER }}         # e.g. deploy
          port:        22
          key_path:    ~/.ssh/deploy_key               # ← must match above
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}  # updated SHA256:… value
          debug:       true
          script: |
            set -e
            cd /home/yoforexai
            git pull origin main
            pip install --upgrade pip
            pip install -r requirements.txt
            sudo systemctl restart backend.service
