name: CI/CD Deploy YoForex-AI Backend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (just for linting/build if needed)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Debug: Show SSH folder contents
        run: ls -l ~/.ssh

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host:        ${{ secrets.SSH_HOST }}
          username:    ${{ secrets.SSH_USER }}
          port:        22
          key_path:    ~/.ssh/deploy_key
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          debug:       true
          script: |
            set -e
            cd /home/yoforexai
            echo "Pulling latest code..."
            git pull origin main
            echo "Installing Python dependencies..."
            pip install --upgrade pip
            pip install -r requirements.txt
            echo "Restarting backend service..."
            sudo systemctl restart backend.service
