name: CI/CD Deploy YoForex-AI Backend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install SSH private key
        run: |
          mkdir -p ~/.ssh
          # write your private key (from the SSH_PRIVATE_KEY secret) to a file
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Debug: verify key file on runner
        run: |
          echo "Runner ~/.ssh contents:"
          ls -la ~/.ssh

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host:        ${{ secrets.SSH_HOST }}
          username:    ${{ secrets.SSH_USER }}
          port:        22
          key_path:    ~/.ssh/deploy_key
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          debug:       true
          script: |
            set -e
            cd /home/yoforexai
            git pull origin main
            pip install --upgrade pip
            pip install -r requirements.txt
            sudo systemctl restart backend.service
