# .github/workflows/deploy.yml

name: CI/CD Deploy YoForex-AI Backend

# Trigger on pushes to main (change the branch if you use another)
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) (Optional) Run tests or lint
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # 5) Deploy via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}             # e.g. your.server.ip
          username: ${{ secrets.SSH_USER }}         # e.g. ubuntu or deployer
          key: ${{ secrets.SSH_PRIVATE_KEY }}       # your ed25519 private key
          port: 22
          script: |
            cd /home/yoforexai
            git pull origin main
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            # If you use migrations, run them here, e.g.:
            # alembic upgrade head
            sudo systemctl restart backend.service
