name: CI/CD Deploy YoForex-AI Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Install Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Install dependencies
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Write your SSH private key to a file
      - name: Install SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      # 5) Verify that the key file is really there
      - name: Debug: list SSH directory
        run: |
          echo "Contents of ~/.ssh:"
          ls -la ~/.ssh

      # 6) Deploy via SSH
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host:        ${{ secrets.SSH_HOST }}         # e.g. 206.206.127.10
          username:    ${{ secrets.SSH_USER }}         # e.g. deploy
          port:        22
          key_path:    ~/.ssh/deploy_key               # must match the file you wrote
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}  # e.g. SHA256:BVdSKL366dHPKsMrrtLyOg5m0wccZ+bt9OBgGs4FRbo
          debug:       true
          script: |
            set -e
            cd /home/yoforexai
            git pull origin main
            pip install --upgrade pip
            pip install -r requirements.txt
            sudo systemctl restart backend.service
